'use client'

import { useState, useRef, useCallback, DragEvent, ChangeEvent } from 'react'
import type { AnalysisResult } from './api/analyze/route'

type AppState = 'idle' | 'preview' | 'analyzing' | 'results' | 'error'

function EyeIcon() {
  return (
    <svg width="36" height="36" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M2 12C2 12 5 5 12 5C19 5 22 12 22 12C22 12 19 19 12 19C5 19 2 12 2 12Z"
        stroke="#3b82f6"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx="12" cy="12" r="3" stroke="#14b8a6" strokeWidth="2" />
      <circle cx="12" cy="12" r="1" fill="#14b8a6" />
    </svg>
  )
}

function SpinnerIcon() {
  return (
    <div
      style={{
        width: '2rem',
        height: '2rem',
        border: '3px solid rgba(59,130,246,0.2)',
        borderTopColor: '#3b82f6',
        borderRadius: '50%',
        animation: 'spin 0.8s linear infinite',
      }}
    />
  )
}

function ConfidenceBadge({ level }: { level: 'High' | 'Moderate' | 'Low' }) {
  const colors: Record<string, { bg: string; text: string; border: string }> = {
    High: { bg: 'rgba(34,197,94,0.1)', text: '#22c55e', border: 'rgba(34,197,94,0.3)' },
    Moderate: { bg: 'rgba(245,158,11,0.1)', text: '#f59e0b', border: 'rgba(245,158,11,0.3)' },
    Low: { bg: 'rgba(239,68,68,0.1)', text: '#ef4444', border: 'rgba(239,68,68,0.3)' },
  }
  const c = colors[level] || colors.Moderate
  return (
    <span
      style={{
        backgroundColor: c.bg,
        color: c.text,
        border: `1px solid ${c.border}`,
        padding: '2px 10px',
        borderRadius: '9999px',
        fontSize: '0.75rem',
        fontWeight: 600,
        letterSpacing: '0.03em',
      }}
    >
      {level}
    </span>
  )
}

function QualityBadge({ level }: { level: 'Good' | 'Fair' | 'Poor' }) {
  const colors: Record<string, { bg: string; text: string; border: string }> = {
    Good: { bg: 'rgba(34,197,94,0.1)', text: '#22c55e', border: 'rgba(34,197,94,0.3)' },
    Fair: { bg: 'rgba(245,158,11,0.1)', text: '#f59e0b', border: 'rgba(245,158,11,0.3)' },
    Poor: { bg: 'rgba(239,68,68,0.1)', text: '#ef4444', border: 'rgba(239,68,68,0.3)' },
  }
  const c = colors[level] || colors.Fair
  return (
    <span
      style={{
        backgroundColor: c.bg,
        color: c.text,
        border: `1px solid ${c.border}`,
        padding: '2px 10px',
        borderRadius: '9999px',
        fontSize: '0.75rem',
        fontWeight: 600,
      }}
    >
      {level}
    </span>
  )
}

function SectionCard({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div
      style={{
        background: '#111d35',
        border: '1px solid #1e3a5f',
        borderRadius: '0.75rem',
        padding: '1.5rem',
        marginBottom: '1rem',
      }}
    >
      <h3
        style={{
          color: '#94a3b8',
          fontSize: '0.75rem',
          fontWeight: 700,
          textTransform: 'uppercase',
          letterSpacing: '0.1em',
          marginBottom: '0.75rem',
        }}
      >
        {title}
      </h3>
      {children}
    </div>
  )
}

function ResultsPanel({ analysis, imageUrl }: { analysis: AnalysisResult; imageUrl: string }) {
  return (
    <div style={{ marginTop: '2rem' }}>
      {/* Report header */}
      <div
        style={{
          background: 'linear-gradient(135deg, rgba(59,130,246,0.15), rgba(20,184,166,0.1))',
          border: '1px solid rgba(59,130,246,0.3)',
          borderRadius: '0.75rem',
          padding: '1.25rem 1.5rem',
          marginBottom: '1.25rem',
          display: 'flex',
          alignItems: 'center',
          gap: '0.75rem',
        }}
      >
        <EyeIcon />
        <div>
          <div style={{ color: '#f1f5f9', fontWeight: 700, fontSize: '1.1rem' }}>OCT Analysis Report</div>
          <div style={{ color: '#94a3b8', fontSize: '0.85rem' }}>Generated by OCT Vision AI</div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1rem' }}>
        {/* Scan preview */}
        <div
          style={{
            background: '#111d35',
            border: '1px solid #1e3a5f',
            borderRadius: '0.75rem',
            padding: '1rem',
            display: 'flex',
            flexDirection: 'column',
            gap: '0.5rem',
          }}
        >
          <p style={{ color: '#94a3b8', fontSize: '0.75rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em' }}>
            Analyzed Image
          </p>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imageUrl}
            alt="Analyzed OCT scan"
            style={{ width: '100%', borderRadius: '0.5rem', objectFit: 'contain', maxHeight: '200px' }}
          />
        </div>

        {/* Scan metadata */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <SectionCard title="Scan Type">
            <p style={{ color: '#f1f5f9', fontWeight: 600 }}>{analysis.scanType}</p>
          </SectionCard>
          <SectionCard title="Image Quality">
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' }}>
              <QualityBadge level={analysis.imageQuality} />
              <p style={{ color: '#cbd5e1', fontSize: '0.875rem' }}>{analysis.qualityNote}</p>
            </div>
          </SectionCard>
        </div>
      </div>

      {/* Key Findings */}
      <SectionCard title="Key Findings">
        <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          {analysis.keyFindings.map((finding, i) => (
            <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '0.6rem', color: '#cbd5e1', fontSize: '0.9rem' }}>
              <span style={{ color: '#3b82f6', marginTop: '0.2rem', flexShrink: 0 }}>▸</span>
              {finding}
            </li>
          ))}
        </ul>
      </SectionCard>

      {/* Primary Diagnosis */}
      <SectionCard title="Primary Diagnosis">
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem', flexWrap: 'wrap' }}>
          <span style={{ color: '#f1f5f9', fontWeight: 700, fontSize: '1.05rem' }}>{analysis.primaryDiagnosis.condition}</span>
          <span style={{ color: '#94a3b8', fontSize: '0.8rem' }}>Confidence:</span>
          <ConfidenceBadge level={analysis.primaryDiagnosis.confidence} />
        </div>
        <p style={{ color: '#94a3b8', fontSize: '0.875rem', lineHeight: 1.6 }}>{analysis.primaryDiagnosis.rationale}</p>
      </SectionCard>

      {/* Differential Diagnoses */}
      {analysis.differentialDiagnoses.length > 0 && (
        <SectionCard title="Differential Diagnoses">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {analysis.differentialDiagnoses.map((dd, i) => (
              <div
                key={i}
                style={{
                  background: 'rgba(30,58,95,0.4)',
                  border: '1px solid #1e3a5f',
                  borderRadius: '0.5rem',
                  padding: '0.75rem 1rem',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.35rem', flexWrap: 'wrap' }}>
                  <span style={{ color: '#e2e8f0', fontWeight: 600, fontSize: '0.9rem' }}>{dd.condition}</span>
                  <span style={{ color: '#94a3b8', fontSize: '0.75rem' }}>Likelihood:</span>
                  <ConfidenceBadge level={dd.likelihood} />
                </div>
                {dd.notes && <p style={{ color: '#94a3b8', fontSize: '0.82rem', lineHeight: 1.5 }}>{dd.notes}</p>}
              </div>
            ))}
          </div>
        </SectionCard>
      )}

      {/* Educational Notes */}
      <SectionCard title="Educational Notes">
        <p style={{ color: '#cbd5e1', fontSize: '0.9rem', lineHeight: 1.7 }}>{analysis.educationalNotes}</p>
      </SectionCard>

      {/* Recommended Next Steps */}
      {analysis.recommendedNextSteps.length > 0 && (
        <SectionCard title="Recommended Next Steps">
          <ol style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            {analysis.recommendedNextSteps.map((step, i) => (
              <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '0.75rem', color: '#cbd5e1', fontSize: '0.9rem' }}>
                <span
                  style={{
                    background: 'rgba(20,184,166,0.15)',
                    color: '#14b8a6',
                    border: '1px solid rgba(20,184,166,0.3)',
                    borderRadius: '50%',
                    width: '1.5rem',
                    height: '1.5rem',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '0.75rem',
                    fontWeight: 700,
                    flexShrink: 0,
                  }}
                >
                  {i + 1}
                </span>
                {step}
              </li>
            ))}
          </ol>
        </SectionCard>
      )}

      {/* Disclaimer */}
      <div
        style={{
          background: 'rgba(239,68,68,0.07)',
          border: '1px solid rgba(239,68,68,0.25)',
          borderRadius: '0.75rem',
          padding: '1rem 1.25rem',
          display: 'flex',
          gap: '0.75rem',
          alignItems: 'flex-start',
        }}
      >
        <span style={{ color: '#ef4444', fontSize: '1.1rem', flexShrink: 0 }}>⚠</span>
        <p style={{ color: '#fca5a5', fontSize: '0.82rem', lineHeight: 1.6, margin: 0 }}>
          {analysis.disclaimer ||
            'This analysis is for educational and informational purposes only. It is not a substitute for professional medical evaluation, diagnosis, or treatment. Always consult a qualified ophthalmologist or retina specialist for clinical decision-making.'}
        </p>
      </div>
    </div>
  )
}

export default function Home() {
  const [state, setState] = useState<AppState>('idle')
  const [imageFile, setImageFile] = useState<File | null>(null)
  const [imageUrl, setImageUrl] = useState<string>('')
  const [isDragOver, setIsDragOver] = useState(false)
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null)
  const [errorMessage, setErrorMessage] = useState<string>('')

  const fileInputRef = useRef<HTMLInputElement>(null)
  const cameraInputRef = useRef<HTMLInputElement>(null)

  const handleFileSelect = useCallback((file: File) => {
    if (!file.type.startsWith('image/')) {
      setErrorMessage('Please upload an image file.')
      setState('error')
      return
    }
    setImageFile(file)
    const url = URL.createObjectURL(file)
    setImageUrl(url)
    setState('preview')
    setAnalysis(null)
    setErrorMessage('')
  }, [])

  const onFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) handleFileSelect(file)
  }

  const onDragOver = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault()
    setIsDragOver(true)
  }

  const onDragLeave = () => setIsDragOver(false)

  const onDrop = (e: DragEvent<HTMLDivElement>) => {
    e.preventDefault()
    setIsDragOver(false)
    const file = e.dataTransfer.files?.[0]
    if (file) handleFileSelect(file)
  }

  const handleAnalyze = async () => {
    if (!imageFile) return
    setState('analyzing')
    setErrorMessage('')

    const formData = new FormData()
    formData.append('image', imageFile)

    try {
      const res = await fetch('/api/analyze', { method: 'POST', body: formData })
      const data = await res.json()

      if (!res.ok || data.error) {
        setErrorMessage(data.error || 'Analysis failed. Please try again.')
        setState('error')
        return
      }

      setAnalysis(data.analysis)
      setState('results')
    } catch {
      setErrorMessage('Network error. Please check your connection and try again.')
      setState('error')
    }
  }

  const handleReset = () => {
    if (imageUrl) URL.revokeObjectURL(imageUrl)
    setImageFile(null)
    setImageUrl('')
    setAnalysis(null)
    setErrorMessage('')
    setState('idle')
    if (fileInputRef.current) fileInputRef.current.value = ''
    if (cameraInputRef.current) cameraInputRef.current.value = ''
  }

  const handleNewScan = () => {
    if (imageUrl) URL.revokeObjectURL(imageUrl)
    setImageFile(null)
    setImageUrl('')
    setAnalysis(null)
    setErrorMessage('')
    setState('idle')
  }

  return (
    <div style={{ minHeight: '100vh', background: '#0a0f1e', color: '#f1f5f9' }}>
      {/* Header */}
      <header
        style={{
          background: 'rgba(13,21,38,0.9)',
          backdropFilter: 'blur(12px)',
          borderBottom: '1px solid #1e3a5f',
          position: 'sticky',
          top: 0,
          zIndex: 50,
          padding: '0 1.5rem',
        }}
      >
        <div style={{ maxWidth: '900px', margin: '0 auto', display: 'flex', alignItems: 'center', gap: '0.75rem', height: '4rem' }}>
          <EyeIcon />
          <div>
            <span
              style={{
                fontWeight: 800,
                fontSize: '1.2rem',
                background: 'linear-gradient(135deg, #3b82f6, #14b8a6)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              OCT Vision AI
            </span>
            <span style={{ color: '#475569', fontSize: '0.8rem', marginLeft: '0.75rem', display: 'none' }} className="sm:inline">
              Intelligent Retinal Analysis
            </span>
          </div>
          {(state === 'results' || state === 'preview') && (
            <button
              onClick={handleNewScan}
              style={{
                marginLeft: 'auto',
                background: 'rgba(59,130,246,0.1)',
                color: '#3b82f6',
                border: '1px solid rgba(59,130,246,0.3)',
                padding: '0.4rem 1rem',
                borderRadius: '0.5rem',
                fontSize: '0.85rem',
                fontWeight: 600,
                cursor: 'pointer',
              }}
            >
              New Scan
            </button>
          )}
        </div>
      </header>

      <main style={{ maxWidth: '900px', margin: '0 auto', padding: '2rem 1.5rem' }}>
        {/* Hero */}
        <div style={{ textAlign: 'center', marginBottom: '2.5rem' }}>
          <h1
            style={{
              fontSize: 'clamp(1.75rem, 5vw, 2.75rem)',
              fontWeight: 800,
              lineHeight: 1.2,
              marginBottom: '1rem',
            }}
          >
            <span
              style={{
                background: 'linear-gradient(135deg, #3b82f6, #14b8a6)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
              }}
            >
              AI-Powered OCT
            </span>
            <br />
            <span style={{ color: '#f1f5f9' }}>Retinal Scan Analysis</span>
          </h1>
          <p style={{ color: '#94a3b8', fontSize: '1rem', maxWidth: '600px', margin: '0 auto', lineHeight: 1.7 }}>
            Upload an OCT scan and receive an instant structured analysis covering retinal layers, pathological findings, differential
            diagnoses, and educational insights — powered by Claude AI.
          </p>

          {/* Feature pills */}
          <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', flexWrap: 'wrap', marginTop: '1.25rem' }}>
            {['Macular OCT', 'Optic Nerve OCT', 'Retinal Thickness', 'AMD Detection', 'Fluid Analysis'].map((tag) => (
              <span
                key={tag}
                style={{
                  background: 'rgba(59,130,246,0.08)',
                  color: '#64748b',
                  border: '1px solid #1e3a5f',
                  padding: '4px 12px',
                  borderRadius: '9999px',
                  fontSize: '0.78rem',
                }}
              >
                {tag}
              </span>
            ))}
          </div>
        </div>

        {/* Upload Zone */}
        {state === 'idle' && (
          <div
            onDragOver={onDragOver}
            onDragLeave={onDragLeave}
            onDrop={onDrop}
            onClick={() => fileInputRef.current?.click()}
            style={{
              border: `2px dashed ${isDragOver ? '#3b82f6' : '#1e3a5f'}`,
              borderRadius: '1rem',
              padding: '3rem 2rem',
              textAlign: 'center',
              cursor: 'pointer',
              background: isDragOver ? 'rgba(59,130,246,0.05)' : 'rgba(17,29,53,0.5)',
              transition: 'all 0.2s ease',
              marginBottom: '1.5rem',
            }}
          >
            <input ref={fileInputRef} type="file" accept="image/*" onChange={onFileChange} style={{ display: 'none' }} />
            <input ref={cameraInputRef} type="file" accept="image/*" capture="environment" onChange={onFileChange} style={{ display: 'none' }} />

            <div style={{ marginBottom: '1rem' }}>
              <svg width="48" height="48" viewBox="0 0 24 24" fill="none" style={{ margin: '0 auto 0.75rem' }}>
                <rect x="3" y="3" width="18" height="18" rx="2" stroke="#1e3a5f" strokeWidth="2" />
                <path d="M3 9l4-4 4 4 4-4 4 4" stroke="#3b82f6" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                <circle cx="8.5" cy="13.5" r="1.5" stroke="#14b8a6" strokeWidth="2" />
              </svg>
              <p style={{ color: '#f1f5f9', fontWeight: 600, fontSize: '1.05rem', marginBottom: '0.35rem' }}>
                {isDragOver ? 'Drop your OCT scan here' : 'Drag & drop your OCT scan'}
              </p>
              <p style={{ color: '#475569', fontSize: '0.85rem' }}>or click to browse files</p>
            </div>

            <div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'center', flexWrap: 'wrap' }}>
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  fileInputRef.current?.click()
                }}
                style={{
                  background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
                  color: 'white',
                  padding: '0.6rem 1.5rem',
                  borderRadius: '0.5rem',
                  fontWeight: 600,
                  border: 'none',
                  cursor: 'pointer',
                  fontSize: '0.9rem',
                }}
              >
                Upload OCT Scan
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  cameraInputRef.current?.click()
                }}
                style={{
                  background: 'rgba(20,184,166,0.1)',
                  color: '#14b8a6',
                  padding: '0.6rem 1.5rem',
                  borderRadius: '0.5rem',
                  fontWeight: 600,
                  border: '1px solid rgba(20,184,166,0.3)',
                  cursor: 'pointer',
                  fontSize: '0.9rem',
                }}
              >
                📷 Camera Capture
              </button>
            </div>

            <p style={{ color: '#334155', fontSize: '0.75rem', marginTop: '1rem' }}>
              Supports JPEG, PNG, GIF, WebP · Max 20MB
            </p>
          </div>
        )}

        {/* Preview state */}
        {(state === 'preview' || state === 'analyzing' || state === 'results') && imageUrl && (
          <div>
            {state === 'preview' && (
              <div
                style={{
                  background: '#111d35',
                  border: '1px solid #1e3a5f',
                  borderRadius: '1rem',
                  padding: '1.5rem',
                  marginBottom: '1.5rem',
                  textAlign: 'center',
                }}
              >
                <p style={{ color: '#94a3b8', fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '1rem' }}>
                  Scan Preview
                </p>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={imageUrl}
                  alt="OCT scan preview"
                  style={{
                    maxWidth: '100%',
                    maxHeight: '400px',
                    objectFit: 'contain',
                    borderRadius: '0.5rem',
                    margin: '0 auto',
                    display: 'block',
                    border: '1px solid #1e3a5f',
                  }}
                />
                {imageFile && (
                  <p style={{ color: '#475569', fontSize: '0.8rem', marginTop: '0.75rem' }}>
                    {imageFile.name} · {(imageFile.size / 1024).toFixed(0)} KB
                  </p>
                )}
                <div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'center', marginTop: '1.25rem', flexWrap: 'wrap' }}>
                  <button
                    onClick={handleAnalyze}
                    style={{
                      background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
                      color: 'white',
                      padding: '0.75rem 2.5rem',
                      borderRadius: '0.5rem',
                      fontWeight: 700,
                      border: 'none',
                      cursor: 'pointer',
                      fontSize: '1rem',
                    }}
                  >
                    Analyze Scan →
                  </button>
                  <button
                    onClick={handleReset}
                    style={{
                      background: 'rgba(30,58,95,0.5)',
                      color: '#94a3b8',
                      padding: '0.75rem 1.5rem',
                      borderRadius: '0.5rem',
                      fontWeight: 600,
                      border: '1px solid #1e3a5f',
                      cursor: 'pointer',
                      fontSize: '0.9rem',
                    }}
                  >
                    Change Image
                  </button>
                </div>
              </div>
            )}

            {state === 'analyzing' && (
              <div
                style={{
                  background: '#111d35',
                  border: '1px solid #1e3a5f',
                  borderRadius: '1rem',
                  padding: '3rem 2rem',
                  textAlign: 'center',
                  marginBottom: '1.5rem',
                }}
              >
                <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '1.25rem' }}>
                  <SpinnerIcon />
                </div>
                <p style={{ color: '#f1f5f9', fontWeight: 600, fontSize: '1.05rem', marginBottom: '0.4rem' }}>
                  Analyzing OCT Scan...
                </p>
                <p style={{ color: '#475569', fontSize: '0.875rem' }}>
                  Claude AI is examining retinal layers and identifying pathologies
                </p>
                <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center', flexWrap: 'wrap', marginTop: '1.25rem' }}>
                  {['Assessing image quality', 'Identifying layers', 'Detecting pathology', 'Generating report'].map((step, i) => (
                    <span
                      key={i}
                      style={{
                        background: 'rgba(59,130,246,0.08)',
                        color: '#64748b',
                        border: '1px solid #1e3a5f',
                        padding: '4px 12px',
                        borderRadius: '9999px',
                        fontSize: '0.75rem',
                      }}
                    >
                      {step}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {state === 'results' && analysis && (
              <ResultsPanel analysis={analysis} imageUrl={imageUrl} />
            )}
          </div>
        )}

        {/* Error State */}
        {state === 'error' && (
          <div
            style={{
              background: 'rgba(239,68,68,0.07)',
              border: '1px solid rgba(239,68,68,0.3)',
              borderRadius: '1rem',
              padding: '2rem',
              textAlign: 'center',
              marginBottom: '1.5rem',
            }}
          >
            <div style={{ fontSize: '2rem', marginBottom: '0.75rem' }}>⚠️</div>
            <p style={{ color: '#fca5a5', fontWeight: 600, marginBottom: '0.5rem', fontSize: '1rem' }}>Analysis Failed</p>
            <p style={{ color: '#f87171', fontSize: '0.875rem', marginBottom: '1.5rem', maxWidth: '500px', margin: '0 auto 1.5rem' }}>
              {errorMessage}
            </p>
            <div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'center', flexWrap: 'wrap' }}>
              {imageFile && (
                <button
                  onClick={() => { setState('preview') }}
                  style={{
                    background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
                    color: 'white',
                    padding: '0.6rem 1.5rem',
                    borderRadius: '0.5rem',
                    fontWeight: 600,
                    border: 'none',
                    cursor: 'pointer',
                  }}
                >
                  Try Again
                </button>
              )}
              <button
                onClick={handleReset}
                style={{
                  background: 'rgba(30,58,95,0.5)',
                  color: '#94a3b8',
                  padding: '0.6rem 1.5rem',
                  borderRadius: '0.5rem',
                  fontWeight: 600,
                  border: '1px solid #1e3a5f',
                  cursor: 'pointer',
                }}
              >
                Upload New Image
              </button>
            </div>
          </div>
        )}

        {/* How it works (shown in idle state) */}
        {state === 'idle' && (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem', marginTop: '0.5rem' }}>
            {[
              { icon: '📤', title: 'Upload', desc: 'Upload any OCT scan image from your device or capture with camera' },
              { icon: '🔬', title: 'Analyze', desc: 'Claude AI examines retinal anatomy, identifies layers and pathologies' },
              { icon: '📋', title: 'Report', desc: 'Get a structured medical-style report with diagnoses and next steps' },
            ].map(({ icon, title, desc }) => (
              <div
                key={title}
                style={{
                  background: '#111d35',
                  border: '1px solid #1e3a5f',
                  borderRadius: '0.75rem',
                  padding: '1.25rem',
                  textAlign: 'center',
                }}
              >
                <div style={{ fontSize: '1.75rem', marginBottom: '0.6rem' }}>{icon}</div>
                <p style={{ color: '#f1f5f9', fontWeight: 700, marginBottom: '0.4rem' }}>{title}</p>
                <p style={{ color: '#64748b', fontSize: '0.82rem', lineHeight: 1.5 }}>{desc}</p>
              </div>
            ))}
          </div>
        )}
      </main>

      {/* Footer */}
      <footer
        style={{
          borderTop: '1px solid #1e3a5f',
          marginTop: '4rem',
          padding: '2rem 1.5rem',
          textAlign: 'center',
        }}
      >
        <div style={{ maxWidth: '700px', margin: '0 auto' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem', marginBottom: '0.75rem' }}>
            <EyeIcon />
            <span style={{ color: '#475569', fontWeight: 600, fontSize: '0.875rem' }}>OCT Vision AI</span>
          </div>
          <p style={{ color: '#334155', fontSize: '0.78rem', lineHeight: 1.7 }}>
            <strong style={{ color: '#475569' }}>Medical Disclaimer:</strong> OCT Vision AI is an educational tool only. All analyses are
            AI-generated and are not intended to diagnose, treat, cure, or prevent any medical condition. This tool does not replace the
            judgment of a qualified ophthalmologist or other licensed healthcare professional. Never disregard professional medical advice
            or delay seeking it based on information provided by this application.
          </p>
        </div>
      </footer>

      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  )
}
